---
title: Bayesian birders
author: Kevin Soo
date: '2021-06-07'
slug: bayesian-birders
categories:
  - General
tags:
  - birds
  - outdoors
---

After spending so much time in front of screens for most of 2020, I’ve tried to make space for more screenless activities that were pandemic-compatible. Evelyn and I got into birding late last year, and have been doing it pretty actively for most of 2021. We’ve been keeping track of our birding adventures on Instagram @[OurBigYear](https://www.instagram.com/ourbigyear/).[^1] Besides the physical and mental health benefits of birding, it’s also an activity that suits data scientists.

Bird identification is basically reasoning using Bayesian statistics. Birders aren’t explicitly performing probabilistic computations when watching for birds, but everyone possesses intuitive cognitive abilities that approximate such computations.[^2]

When birding, birders first consider the distributions of bird species over geographical regions and habitats, which change depending on the time of day and year. A birder might not know the precise distributions, but they usually have a sense that at this time of the year in their part of the world, it is likelier to encounter a [Northern Cardinal](https://www.allaboutbirds.org/guide/Northern_Cardinal/overview) than an [Eastern Bluebird](https://www.allaboutbirds.org/guide/Eastern_Bluebird/overview), i.e. *P*(Northern Cardinal) > *P*(Eastern Bluebird). These are referred to as *priors*: The prior knowledge you have before identifying any particular specimen.

When a birder catches a partial glimpse of a bird (or hears its call), they consider the likelihood that it was a particular species given the evidence they saw (or heard). If they see a flash of red, they know it is likelier to belong to a Northern Cardinal than to any other species in the area, i.e. *P*(Red plumage|Northern Cardinal) is really high. This is referred to as the *likelihood* or fit of a species to the observed evidence. 

Using [Bayes’ theorem](https://en.wikipedia.org/wiki/Bayes%27_theorem), a birder can use the likelihood of a feature belonging to a particular species to update their prior probability of seeing that particular bird, resulting in a *posterior probability* – *P*(Northern Cardinal|Red plumage) – the probability the bird they saw was of a particular species given the evidence. The posterior probability quantifies their confidence that the specimen they saw is of a particular species, given the evidence they observed. If Northern Cardinals are the only common species with red plumage in the area, seeing a flash of red is going to lead to *P*(Northern Cardinal|Red plumage) pretty close to 1 (i.e. they will be practically certain of what they saw). 

In reality, birding is both more and less complicated than this. It’s more complicated because birds can veer beyond their expected distributions, because we are sometimes mistaken about what we've seen or heard, and because some evidence is common to multiple species of bird (e.g., if there are multiple species with red plumage in the area, seeing red plumage won’t be as helpful in identifying the species you saw). On the other hand, birding is also easier because we almost always observe multiple features simultaneously while birding that help us with identification (e.g. plumage color *and* size *and* behavior), and because our minds are adept and practiced at carrying out these types of computations with minimal effort.

[^1]: A "[Big Year](https://en.wikipedia.org/wiki/Big_year)" is a challenge birders take on to identify as many species as they can in a calendar year). The [top North American birders](https://www.audubon.org/news/two-guys-just-broke-north-american-big-year-record-how) see upwards of 700-800 species, so I hesitate to say what we’re doing counts as a Big Year. As of this post, we’re at 129 species for the year.

[^2]: The general domain of my research in graduate school was how people used intuitive mental heuristics to approximate more sophisticated probabilistic computations.